### ISSUE TITLE
Any conversion using pandas.DataFrame with explicit dshape fails

### ISSUE THREAD

**Issue by educhana** [blaze/odo#379]
Tested with odo 0.3.4 and 0.3.3 under anaconda python 3.4

Code to reproduce the issue:
```python
from __future__ import print_function
from odo import odo, discover

data = [
    ("1", 3.4),
    ("a", 5.0),
]

print(discover(data))
dshape = "var * {k: string, v: float64}"

# OK
t1 = odo(data, tuple)
print(t1)

# OK
t2 = odo(data, tuple, dshape=dshape)
print(t2)

# OK
t3 = odo(data, "test.csv")
print(t3)

# FAIL: goes thru pandas.DataFrame and dshape passed
t4 = odo(data, "test.csv", dshape=dshape)
print(t4)
```

trace:
```bash
2 * (string, float64)
(('1', 3.4), ('a', 5.0))
(('1', 3.4), ('a', 5.0))
<odo.backends.csv.CSV object at 0x0000000008780DA0>
Traceback (most recent call last):
  File "C:/Users/n64038/.PyCharm50/config/scratches/scratch_13", line 25, in <module>
    t4 = odo(data, "test.csv", dshape=dshape)
  File "D:\bin\Anaconda3\lib\site-packages\odo\odo.py", line 90, in odo
    return into(target, source, **kwargs)
  File "D:\bin\Anaconda3\lib\site-packages\multipledispatch\dispatcher.py", line 164, in __call__
    return func(*args, **kwargs)
  File "D:\bin\Anaconda3\lib\site-packages\odo\into.py", line 111, in into_string
    return into(a, b, dshape=dshape, **kwargs)
  File "D:\bin\Anaconda3\lib\site-packages\multipledispatch\dispatcher.py", line 164, in __call__
    return func(*args, **kwargs)
  File "D:\bin\Anaconda3\lib\site-packages\odo\into.py", line 100, in into_object
    return append(target, source, dshape=dshape, **kwargs)
  File "D:\bin\Anaconda3\lib\site-packages\multipledispatch\dispatcher.py", line 164, in __call__
    return func(*args, **kwargs)
  File "D:\bin\Anaconda3\lib\site-packages\odo\backends\csv.py", line 202, in append_object_to_csv
    append(c, convert(chunks(pd.DataFrame), seq, **kwargs), **kwargs)
  File "D:\bin\Anaconda3\lib\site-packages\odo\core.py", line 30, in __call__
    return _transform(self.graph, *args, **kwargs)
  File "D:\bin\Anaconda3\lib\site-packages\odo\core.py", line 46, in _transform
    x = f(x, excluded_edges=excluded_edges, **kwargs)
  File "D:\bin\Anaconda3\lib\site-packages\odo\convert.py", line 215, in iterator_to_DataFrame_chunks
    df = convert(pd.DataFrame, first, **kwargs)
  File "D:\bin\Anaconda3\lib\site-packages\odo\core.py", line 30, in __call__
    return _transform(self.graph, *args, **kwargs)
  File "D:\bin\Anaconda3\lib\site-packages\odo\core.py", line 46, in _transform
    x = f(x, excluded_edges=excluded_edges, **kwargs)
  File "D:\bin\Anaconda3\lib\site-packages\odo\convert.py", line 30, in numpy_to_dataframe
    return pd.DataFrame(x, columns=getattr(dshape.measure, 'names', None))
AttributeError: 'str' object has no attribute 'measure'
```

**Comment by llllllllll** [comment]
This appears to be fixed on master. We should be releasing the newest version of odo (0.4.0) very soon.

```python
In [1]: data = [
   ...:     ("1", 3.4),
   ...:     ("a", 5.0),
   ...: ]

In [2]: dshape = "var * {k: string, v: float64}"

Int [3]: t4 = odo(data, "test.csv", dshape=dshape)

In [4]: bz.Data(t4)
Out[4]: 
   k    v
0  1  3.4
1  a  5.0

```
