### ISSUE TITLE
Using drop to overwrite data to postgresql

### ISSUE THREAD

**Issue by Jeffrey04** [blaze/odo#380]
I am having a very inconsistent result when trying to do `odo()` to postgresql target. As I can't find a way to overwrite existing record, I use `drop()` before calling `odo()`.

```
drop('postgresql://.....')
odo(dataframe, 'postgresql://....')
```

Then I start getting exceptions because the table does not exist, hence I did this

```
try:
    drop('postgresql://....')
except ValueError:
    pass

odo(dataframe, 'postgresql://....')
```

So when I ran the code above the first time, I got exception for `odo()` saying my table does not exist. However, when I ran the same code the second time, the exception didn't get raised again, and the newly created table was properly populated. Am I doing anything wrong?

I am on odo 0.3.4 and python 3.4.3 on ubuntu 14.04.3

**Comment by Jeffrey04** [comment]
My current workaround to this problem is to manually issuing a `DROP TABLE IF EXISTS` statement

**Comment by llllllllll** [comment]
When you say overwrite an existing record, do you mean update a single tuple or the whole table? It looks like you are trying to replace the whole table so this seems correct. Can you post a terminal session where you are running into this issue with the full stack traces? Make sure to remove any credentials from the postgresql connection strings.

**Comment by Jeffrey04** [comment]
i was trying to overwrite the whole table, not a single tuple (:

```
Traceback (most recent call last):
  File "address/preprocessor.py", line 212, in <module>
    if __name__ == '__main__': main()
  File "address/preprocessor.py", line 201, in main
    index == 0)
  File "address/preprocessor.py", line 176, in data_dump
    odo(data, '{}::{}'.format(connection.engine.url, table_name))
  File "/home/jeffrey04/machine-learning/lib/python3.4/site-packages/odo/odo.py", line 90, in odo
    return into(target, source, **kwargs)
  File "/home/jeffrey04/machine-learning/lib/python3.4/site-packages/multipledispatch/dispatcher.py", line 164, in __call
__
    return func(*args, **kwargs)
  File "/home/jeffrey04/machine-learning/lib/python3.4/site-packages/odo/into.py", line 111, in into_string
    return into(a, b, dshape=dshape, **kwargs)
  File "/home/jeffrey04/machine-learning/lib/python3.4/site-packages/multipledispatch/dispatcher.py", line 164, in __call
__
    return func(*args, **kwargs)
  File "/home/jeffrey04/machine-learning/lib/python3.4/site-packages/odo/into.py", line 100, in into_object
    return append(target, source, dshape=dshape, **kwargs)
  File "/home/jeffrey04/machine-learning/lib/python3.4/site-packages/multipledispatch/dispatcher.py", line 164, in __call
__
    return func(*args, **kwargs)
  File "/home/jeffrey04/machine-learning/lib/python3.4/site-packages/odo/backends/sql.py", line 453, in append_anything_t
o_sql_Table
    return append(t, convert(Iterator, o, **kwargs), **kwargs)
  File "/home/jeffrey04/machine-learning/lib/python3.4/site-packages/multipledispatch/dispatcher.py", line 164, in __call
__
    return func(*args, **kwargs)
  File "/home/jeffrey04/machine-learning/lib/python3.4/site-packages/odo/backends/sql.py", line 413, in append_iterator_t
o_table
    raise ValueError('table %r does not exist' % t.name)
ValueError: table 'nis_data' does not exist```

**Comment by llllllllll** [comment]
Just to make sure I understand, the repro case is:

1. create a table with `odo(DataFrame, 'db_uri')`
1. use `odo.drop('db_uri')` to drop the sql table.
1. attempt step 1 again

I am not able to repro with these steps using postgres:

```python
In [1]: df = pd.DataFrame({'a': list(range(4))*2, 'b': ['apple', 'apple', 'pear', 'banana']*2})

In [2]: df
Out[2]: 
   a       b
0  0   apple
1  1   apple
2  2    pear
3  3  banana
4  0   apple
5  1   apple
6  2    pear
7  3  banana

In [3]: odo(df, 'postgresql://localhost/test::dne')
Out[3]: Table('dne', MetaData(bind=Engine(postgresql://localhost/test)), Column('a', BigInteger(), table=<dne>, nullable=False), Column('b', Text(), table=<dne>), schema=None)

In [4]: from odo import drop

In [5]: drop('postgresql://localhost/test::dne')

In [6]: odo(df, 'postgresql://localhost/test::dne')
Out[6]: Table('dne', MetaData(bind=Engine(postgresql://localhost/test)), Column('a', BigInteger(), table=<dne>, nullable=False), Column('b', Text(), table=<dne>), schema=None)
```

Maybe I am misunderstanding the case. Do you have small minimal working example that I can copy and run? I will most likely not be able to get back to you tonight; I will try to help out tomorrow.

**Comment by Jeffrey04** [comment]
hmm, let me find a way to replicate the problem, and get back to you

**Comment by Jeffrey04** [comment]
So I was able to replicate the problem with the following script

```
import sys

import pandas
from random import random

from blaze import Data
from odo import odo, drop

df = pandas.DataFrame(list(zip([random() for i in range(100)],
                               [random() for i in range(100)])),
                      columns=('A', 'B'))
dsn = 'postgresql://jeffrey04:abc123@localhost:5432/blaze_drop_bug::df'

if int(sys.argv[1]) == 1:
    print('Step 1: Create mock dataset')

    odo(df, dsn)
else:
    print('Step 2: Drop and recreate')

    try:
        drop(dsn)
    except ValueError:
        pass

    odo(df, dsn)
```

Step to replicate:

```
jeffrey04@gideon:~/machine-learning⟫ python3 blaze-drop.py 1
Step 1: Create mock dataset
jeffrey04@gideon:~/machine-learning⟫ python3 blaze-drop.py 2
Step 2: Drop and recreate
Traceback (most recent call last):
  File "blaze-drop.py", line 26, in <module>
    odo(df, dsn)
  File "/home/jeffrey04/machine-learning/lib/python3.4/site-packages/odo/odo.py", line 90, in odo
    return into(target, source, **kwargs)
  File "/home/jeffrey04/machine-learning/lib/python3.4/site-packages/multipledispatch/dispatcher.py", line 164, in __cal
l__
    return func(*args, **kwargs)
  File "/home/jeffrey04/machine-learning/lib/python3.4/site-packages/odo/into.py", line 111, in into_string
    return into(a, b, dshape=dshape, **kwargs)
  File "/home/jeffrey04/machine-learning/lib/python3.4/site-packages/multipledispatch/dispatcher.py", line 164, in __cal
l__
    return func(*args, **kwargs)
  File "/home/jeffrey04/machine-learning/lib/python3.4/site-packages/odo/into.py", line 100, in into_object
    return append(target, source, dshape=dshape, **kwargs)
  File "/home/jeffrey04/machine-learning/lib/python3.4/site-packages/multipledispatch/dispatcher.py", line 164, in __cal
l__
    return func(*args, **kwargs)
  File "/home/jeffrey04/machine-learning/lib/python3.4/site-packages/odo/backends/sql.py", line 453, in append_anything_
to_sql_Table
    return append(t, convert(Iterator, o, **kwargs), **kwargs)
  File "/home/jeffrey04/machine-learning/lib/python3.4/site-packages/multipledispatch/dispatcher.py", line 164, in __cal
l__
    return func(*args, **kwargs)
  File "/home/jeffrey04/machine-learning/lib/python3.4/site-packages/odo/backends/sql.py", line 413, in append_iterator_
to_table
    raise ValueError('table %r does not exist' % t.name)
ValueError: table 'df' does not exist
```

**Comment by branning** [comment]
I tracked this down, it's related to the memoization of the SqlAlchemy metadata. After the `drop`, SqlAlchemy still reports that the table exists, even though `psql` reports that the table is already gone. I modified the minimal example to work on my machine, and it works Ok after removing the memoized call to `SqlAlchemy.metadata`.

It seems to me that we may not want to be memoizing SqlAlchemy metadata at all. It's likely this is due to my lack of complete understanding. But my humble assessment is that this function isn't pure, and caching the result is going to give unpredictable results.

**Comment by cpcloud** [comment]
I'll add a test for this to #328

**Comment by cpcloud** [comment]
Closed by #328

**Comment by Jeffrey04** [comment]
Thanks for the fix (:

**Comment by llllllllll** [comment]
By not memoizing the metadata we are opening far more connections than we previously did. One of my applications was passing uri strings around everywhere and only materializing to a table or schema when needed with resource. We are now never cleaning up the old metadata objects and I am hitting connection limit issues.
