### ISSUE TITLE
Error when converting from Postgres database with OID type

### ISSUE THREAD

**Issue by suchow** [blaze/odo#527]
While converting a Postgres database to a pandas DataFrame using odo version 0.5.0, I got the following error:

```
>>> from odo import odo
>>> import pandas as pd
>>> odo("postgresql://postgres@localhost/dallinger", pd.DataFrame)
Blaze does not understand a SQLAlchemy type.
Blaze provided the following error:
	No SQL-datashape match for type OID
Skipping.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "[redacted]/odo/odo.py", line 91, in odo
    return into(target, source, **kwargs)
  File "[redacted]/multipledispatch/dispatcher.py", line 164, in __call__
    return func(*args, **kwargs)
  File "[redacted]/odo/into.py", line 43, in wrapped
    return f(*args, **kwargs)
  File "[redacted]/odo/into.py", line 149, in into_string_string
    return into(a, resource(b, **kwargs), **kwargs)
  File "[redacted]/multipledispatch/dispatcher.py", line 164, in __call__
    return func(*args, **kwargs)
  File "[redacted]/odo/into.py", line 43, in wrapped
    return f(*args, **kwargs)
  File "[redacted]/odo/into.py", line 53, in into_type
    return convert(a, b, dshape=dshape, **kwargs)
  File "[redacted]/odo/core.py", line 44, in __call__
    return _transform(self.graph, *args, **kwargs)
  File "[redacted]/odo/core.py", line 57, in _transform
    ooc_types=ooc_types)
  File "[redacted]/odo/core.py", line 92, in path
    pth = nx.shortest_path(g, source=source, target=target, weight='cost')
  File "[redacted]/networkx/algorithms/shortest_paths/generic.py", line 138, in shortest_path
    paths=nx.dijkstra_path(G,source,target,weight)
  File "[redacted]/networkx/algorithms/shortest_paths/weighted.py", line 78, in dijkstra_path
    weight=weight)
  File "[redacted]/networkx/algorithms/shortest_paths/weighted.py", line 296, in single_source_dijkstra
    target=target)
  File "[redacted]/networkx/algorithms/shortest_paths/weighted.py", line 356, in _dijkstra
    for u, e in G_succ[v].items():
KeyError: <class 'sqlalchemy.engine.base.Engine'>
>>>
```

https://www.postgresql.org/docs/8.1/static/datatype-oid.html

**Comment by llllllllll** [comment]
What type do you think this should be converted into when in python, integer?

**Comment by suchow** [comment]
@llllllllll Yeah, I think that's what I would have expected.
