### ISSUE TITLE
Odo 0.5.1 is incompatible with sqlalchemy 1.4 on Arch Linux

### ISSUE THREAD

**Issue by carlosal1015** [blaze/odo#637]
### Description

Hi, over Arch Linux we install both [`python-odo-0.5.1-1`](https://aur.archlinux.org/packages/python-odo) and [`python-sqlalchemy-1.4.25-1`](https://archlinux.org/packages/community/x86_64/python-sqlalchemy), but if 

### Steps to reproduce

Install `odo` from AUR and sqlalchemy from official repositories as follows
```
$ yay -Syyu python-odo
$ sudo pacman -S python-sqlalchemy
sudo pacman -S python-sqlalchemy
resolving dependencies...
looking for conflicting packages...

Packages (2) python-greenlet-1.1.2-1  python-sqlalchemy-1.4.25-1

Total Download Size:    1.95 MiB
Total Installed Size:  11.15 MiB

:: Proceed with installation? [Y/n] 
:: Retrieving packages...
 python-greenlet-1.1.2-1-x86_64                                                   85.5 KiB   111 KiB/s 00:01 [-----------------------------------------------------------------] 100%
 python-sqlalchemy-1.4.25-1-x86_64                                              1912.3 KiB  1285 KiB/s 00:01 [-----------------------------------------------------------------] 100%
 Total (2/2)                                                                    
```
wait to finish installation and run:

```
[aur@297cae3df7e3 ~]$ python
Python 3.9.7 (default, Oct 10 2021, 15:13:22) 
[GCC 11.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import odo
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.9/site-packages/odo/__init__.py", line 39, in <module>
    from .backends import sql
  File "/usr/lib/python3.9/site-packages/odo/backends/sql.py", line 318, in <module>
    @discover.register(sa.engine.RowProxy)
AttributeError: module 'sqlalchemy.engine' has no attribute 'RowProxy'
>>> 
```

### Properties

```
Name            : python-odo
Version         : 0.5.1-1
Description     : Data Migration for the Blaze Project
Architecture    : any
URL             : https://github.com/blaze/odo
Licenses        : BSD
Groups          : None
Provides        : None
Depends On      : python-datashape  python-pandas  python-dask  python-networkx
Optional Deps   : None
Required By     : None
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 404.83 KiB
Packager        : Unknown Packager
Build Date      : Fri 26 Nov 2021 11:13:23 PM -05
Install Date    : Fri 26 Nov 2021 11:13:29 PM -05
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : None
```

```
Name            : python-sqlalchemy
Version         : 1.4.25-1
Description     : Python SQL toolkit and Object Relational Mapper
Architecture    : x86_64
URL             : https://www.sqlalchemy.org/
Licenses        : MIT
Groups          : None
Provides        : None
Depends On      : python  python-greenlet
Optional Deps   : python-psycopg2: connect to PostgreSQL database
Required By     : None
Optional For    : python-dask  python-pandas
Conflicts With  : None
Replaces        : None
Installed Size  : 10.76 MiB
Packager        : Jelle van der Waa <jelle@archlinux.org>
Build Date      : Sun 03 Oct 2021 09:33:09 AM -05
Install Date    : Fri 26 Nov 2021 11:23:14 PM -05
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature
```

**Comment by nydelzaf** [comment]
Facing this issue. No fix from the maintainers ?
